majorApp/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.searchPage, name="searchPage"),
    path('overview/', views.overview, name="overview"),
    path('navigation/', views.navigation, name="navigation"),
    path('candlestick_chart/', views.candlestick_chart, name='candlestick_chart'),
]

majorPro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("majorApp.urls", "majorApp"), namespace="majorApp")),
]

majorApp/models.py
from django.db import models

# Create your models here.

majorApp/views.py
import io
from django.shortcuts import render, redirect
from django.http import HttpResponse
import yfinance as yf
import pandas as pd
import mplfinance as mpf
import matplotlib.pyplot as plt
from io import BytesIO
import plotly.graph_objects as go
import csv
from matplotlib.backends.backend_agg import FigureCanvasAgg
import logging
import plotly.express as px
from plotly.subplots import make_subplots

from .prediction import fetch_and_preprocess, create_sequences, build_model, predict_stock_prices


def searchPage(request):
    csv_file = 'majorApp/static/CSV/companies.csv'  # Path to your CSV file
    options = []
    with open(csv_file, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            options.append({'value': row['SYMBOL'], 'text': row['NAME OF COMPANY']})

    return render(request, 'majorApp/searchPage.html', {'options': options})


def overview(request):
    if request.method == 'POST':
        c_name = request.POST.get('c_name')
        cname = request.session['cname'] = c_name
        if len(c_name) == 0:
            alert_message = True
            return render(request, 'majorApp/searchPage.html', {'alert_message': alert_message})
        else:
            c_name += ".NS"
            name = yf.Ticker(c_name)
            mutual_fund_holders = name.mutualfund_holders
            fund_names = mutual_fund_holders['Holder']
            fund_percentages = mutual_fund_holders['pctHeld']
            if fund_names is not None and fund_percentages is not None:
                pie = go.Figure(data=[go.Pie(labels=fund_names, values=fund_percentages)])
                pie.update_layout(title=f'Mutual Fund Holders Distribution for {cname}', width=1200)
                pie_chart = pie.to_html(full_html=False)
            else:
                pie = go.Figure(data=[go.Pie(labels=['No Data'], values=[100])])
                pie.update_layout(title=f'No Data of Mutual Fund Holders Distribution for {cname}', width=1200)
                pie_chart = pie.to_html(full_html=False)
            context = {'summary': get_summary(c_name).replace(';', ','),
                       'c_name': c_name,
                       'Total_Employees': name.info.get('fullTimeEmployees'),
                       'industry': name.info.get('industry'),
                       'sector': name.info.get('sector'),
                       'website': name.info.get('website'),
                       'pie_chart': pie_chart}
            return render(request, 'majorApp/overview.html', context)
    return render(request, 'majorApp/searchPage.html')


def navigation(request):
    if request.method == 'POST':
        cname = request.session.get('cname')
        action = request.POST.get('task')
        # Overview
        if action == 'overview':
            cname += ".NS"
            name = yf.Ticker(cname)
            # Mutualfund Shareholding
            mutual_fund_holders = name.mutualfund_holders
            fund_names = mutual_fund_holders['Holder']
            fund_percentages = mutual_fund_holders['pctHeld']
            print('Hello', fund_names)
            if fund_names is not None and fund_percentages is not None:
                pie = go.Figure(data=[go.Pie(labels=fund_names, values=fund_percentages)])
                pie.update_layout(title=f'Mutual Fund Holders Distribution for {cname}', width=1200)
                pie_chart = pie.to_html(full_html=False)
            else:
                pie = go.Figure(data=[go.Pie(labels=['No Data'], values=[100])])
                pie.update_layout(title=f'No Data of Mutual Fund Holders Distribution for {cname}', width=1200)
                pie_chart = pie.to_html(full_html=False)
            context = {'summary': get_summary(cname).replace(';', ','),
                       'c_name': cname,
                       'Total_Employees': name.info.get('fullTimeEmployees'),
                       'industry': name.info.get('industry'),
                       'sector': name.info.get('sector'),
                       'website': name.info.get('website'),
                       'pie_chart': pie_chart}
            return render(request, 'majorApp/overview.html', context)

        # Financials
        elif action == 'financials':
            cname += ".NS"
            stock = yf.Ticker(cname)
            balance_sheet = stock.balance_sheet
            financials = stock.financials

            # Gross Profit
            if not financials.empty:
                total_revenue = financials.loc['Total Revenue'][0] if 'Total Revenue' in financials.index else None
                cost_of_revenue = financials.loc['Cost Of Revenue'][
                    0] if 'Cost Of Revenue' in financials.index else None

                if all([total_revenue, cost_of_revenue]):
                    gross_profit = total_revenue - cost_of_revenue
                else:
                    gross_profit = 'NA'
            else:
                gross_profit = 'NA'

            # EBITDA
            if not financials.empty:
                operating_income = financials.loc['Operating Income'][
                    0] if 'Operating Income' in financials.index else None
                depreciation_and_amortization = financials.loc['Depreciation & Amortization'][
                    0] if 'Depreciation & Amortization' in financials.index else None

                if all([operating_income, depreciation_and_amortization]):
                    ebitda = operating_income + depreciation_and_amortization
                else:
                    ebitda = 'NA'
            else:
                ebitda = 'NA'

            # Plotting Total Revenue for Financial Years
            income_stmt = stock.income_stmt
            total_revenue = income_stmt.loc['Total Revenue']
            df_total_rev = total_revenue.reset_index()
            df_total_rev.columns = ['Date', 'Total Revenue']
            df_total_rev['Date'] = pd.to_datetime(df_total_rev['Date'])
            df_total_rev = df_total_rev.sort_values(by='Date').tail(4)
            df_total_rev['Total Revenue (INR Crores)'] = df_total_rev['Total Revenue'] / 1e7
            df_total_rev['Financial Year'] = (df_total_rev['Date'].dt.year - 1).astype(str) + '-' + df_total_rev[
                                                                                                        'Date'].dt.year.astype(
                str).str[2:]
            net_income = income_stmt.loc['Net Income']
            df_net_inc = net_income.reset_index()
            df_net_inc.columns = ['Date', 'Net Income']
            df_net_inc['Date'] = pd.to_datetime(df_net_inc['Date'])
            df_net_inc = df_net_inc.sort_values(by='Date').tail(4)
            df_net_inc['Net Income (INR Crores)'] = df_net_inc['Net Income'] / 1e7
            df_net_inc['Financial Year'] = (df_net_inc['Date'].dt.year - 1).astype(str) + '-' + df_net_inc[
                                                                                                    'Date'].dt.year.astype(
                str).str[2:]
            plots = make_subplots(rows=1, cols=2, shared_yaxes=True,
                                subplot_titles=[f'Total Revenue ({cname})', f'Net Income ({cname})'])
            plots.add_trace(go.Bar(x=df_total_rev['Financial Year'], y=df_total_rev['Total Revenue (INR Crores)'],
                                 marker_color='#2ca02c', name='Total Revenue (INR Crores)'), row=1, col=1)
            plots.add_trace(go.Bar(x=df_net_inc['Financial Year'], y=df_net_inc['Net Income (INR Crores)'],
                                 marker_color='skyblue', name='Net Income (INR Crores)'), row=1, col=2)
            plots.update_layout(
                title=f'{cname} Financial Performance',
                height=600,
                legend_title='Legend',
                title_x=0.5,
                showlegend=True,
            )
            plots.update_xaxes(title_text='Financial Year', row=1, col=1)
            plots.update_xaxes(title_text='Financial Year', row=1, col=2)
            plots.update_yaxes(title_text='Amount (INR Crores)', row=1, col=1)
            year_revenue = plots.to_html(full_html = False)

            # Quaterly Revenue
            quat_income_stmt = stock.quarterly_income_stmt
            quat_total_revenue = quat_income_stmt.loc['Total Revenue']
            df_total_rev = quat_total_revenue.reset_index()
            df_total_rev = df_total_rev.head(5)
            df_total_rev.columns = ['Date', 'Total Revenue']
            df_total_rev['Date'] = pd.to_datetime(df_total_rev['Date'])
            df_total_rev = df_total_rev.sort_values(by='Date')
            df_total_rev['Total Revenue (INR Crores)'] = df_total_rev['Total Revenue'] / 1e7
            df_total_rev['Quarter'] = df_total_rev['Date'].dt.to_period('Q')

            quat_net_income = income_stmt.loc['Net Income']
            df_net_inc = quat_net_income.reset_index()
            df_net_inc = df_net_inc.head(5)
            df_net_inc.columns = ['Date', 'Net Income']
            df_net_inc['Date'] = pd.to_datetime(df_total_rev['Date'])
            df_net_inc = df_net_inc.sort_values(by='Date')
            df_net_inc['Net Income (INR Crores)'] = df_net_inc['Net Income'] / 1e7
            df_net_inc['Quarter'] = df_net_inc['Date'].dt.to_period('Q')
            plots1 = make_subplots(rows=1, cols=2, shared_yaxes=True,
                                subplot_titles=[f'Total Revenue ({cname})', f'Net Income ({cname})'])
            plots1.add_trace(go.Bar(x=df_total_rev['Quarter'].astype(str), y=df_total_rev['Total Revenue (INR Crores)'],
                                 marker_color='#2ca02c', name='Total Revenue (INR Crores)'), row=1, col=1)
            plots1.add_trace(go.Bar(x=df_net_inc['Quarter'].astype(str), y=df_net_inc['Net Income (INR Crores)'],
                                 marker_color='skyblue', name='Net Income (INR Crores)'), row=1, col=2)
            plots1.update_layout(

templates/majorApp/financials.html
{% load static %}

{% load custom_filters %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Investology-Financials{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/financials.css' %}">
    <style>
        .plot-container {
            justify-content: center;
            margin: 50px 50px;
        }
    </style>
</head>
<body>
{% include 'majorApp/navigation.html' %}
{% block content %}
    <div class="container1">
        <div class="header1">
            <h1>{{ company_name }} Financials</h1>
        </div>
        <div class="links1">
            <a href="#">Website: {{website}}</a>
            <a href="#">NSE: {{ company_name }}</a>
        </div>
        <div class="content1">
            <div class="info1">
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Revenue </span>
                        <span class="value1">₹ {{ Revenue|human_readable_large_number }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">GrossProfit</span>
                        <span class="value1">₹ {{ Gross_Profit|human_readable_large_number}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Net Income</span>
                        <span class="value1">₹ {{ Net_Income|human_readable_large_number}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="plot-container">
    <div>{{ year_revenue | safe }}</div>
</div>
<div class="plot-container">
    <div>{{ quat_plot | safe }}</div>
</div>
{% endblock %}

templates/majorApp/fundamentals.html
{% load static %}

{% load custom_filters %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Investology-Fundamentals{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/fundamentals.css' %}">
</head>

<body>
    {% include 'majorApp/navigation.html' %}
    {% block content %}
    <div class="container1" style="background-color: skyblue;">
        <div class="header1">
            <h1>Ideal Metrics for Fundamentals Analysis</h1>
        </div>
        <div class="content1">
            <div class="info1">
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Small Cap Company</span>
                        <span class="value1"> < ₹ 5,000 Cr</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Mid Cap Company</span>
                        <span class="value1">  ₹ 5,000 to ₹ 20,000 Cr</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Large Cap Company</span>
                        <span class="value1"> > ₹ 20,000 Cr</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Market Cap</span>
                        <span class="value1">₹ {{ market_cap|human_readable_large_number }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">PE Ratio</span>
                        <span class="value1"> Best if < 25</span>
                    </div>
                    <div class="col1">
                        <span class="label1">PS Ratio</span>
                        <span class="value1">Best if < 1.5</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">PB</span>
                        <span class="value1">Best if < 3</span>
                    </div>
                    <div class="col1">
                        <span class="label1">OPM</span>
                        <span class="value1">Should be greater than previous Quarter or Year</span>
                    </div>
                    <div class="col1">
                        <span class="label1">NPM</span>
                        <span class="value1">Greater than previous Quarter or Year</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">ROE</span>
                        <span class="value1"> Greater than 20%</span>
                    </div>
                    <div class="col1">
                        <span class="label1">ROA</span>
                        <span class="value1">Greater than 10%</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Total Debt</span>
                        <span class="value1"> As Less As Possible</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Debt/Equity</span>
                        <span class="value1">Less than 0.5</span>
                    </div>
                    <div class="col1">
                        <span class="label1">EPS</span>
                        <span class="value1"> Higher when compared to peers</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Dividend Yeild</span>
                        <span class="value1">Good if above 5%</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container1">
        <div class="header1">
            <h1>{{ company_name }} Fundamentals</h1>
        </div>
        <div class="links1">
            <a href="#">Website: {{website}}</a>
            <a href="#">NSE: {{company_name}}</a>
        </div>
        <div class="content1">
            <div class="info1">
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Market Cap</span>
                        <span class="value1">₹ {{ market_cap|human_readable_large_number }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">PE Ratio</span>
                        <span class="value1">{{ forward_pe|floatformat:2 }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">PS Ratio</span>
                        <span class="value1">{{ price_sales|floatformat:2 }}</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">PB</span>
                        <span class="value1">{{ price_book|floatformat:2 }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">OPM</span>
                        <span class="value1">{{ operating_margin|floatformat:2 }}%</span>
                    </div>
                    <div class="col1">
                        <span class="label1">NPM</span>
                        <span class="value1">{{ profit_margin|floatformat:2 }}%</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">ROE</span>
                        <span class="value1">{{ return_on_equity|floatformat:2 }}%</span>
                    </div>
                    <div class="col1">
                        <span class="label1">ROA</span>
                        <span class="value1">{{ return_on_assets|floatformat:2 }}%</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Total Debt</span>
                        <span class="value1">₹ {{ total_debt|human_readable_large_number}}</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Debt/Equity</span>
                        <span class="value1">{{ debtToEquity | floatformat:2 }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">EPS</span>
                        <span class="value1">{{EPS | floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Dividend Yeild</span>
                        <span class="value1">{{ Dividend_Yield }}%</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">P\FCF</span>
                        <span class="value1">{{ P_FCF }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">EV\EBIDTA</span>
                        <span class="value1">{{ EV_EBITDA }}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">EV\Revenue</span>
                        <span class="value1">{{ EV_Revenue }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/majorApp/navigation.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Investology-Navigation</title>
    <link rel="stylesheet" href="{% static 'css/navigation.css' %}">
</head>
<body>
<!---
    <div class="header">
        <div class="search-container">
	        <form method="post" action="{% url 'majorApp:navigation' %}">
            {% csrf_token %}
                <input type="text" name="cname" placeholder="Search for Company">
                <button type="submit" name="task" value="search">Search</button>
            </form>
	    </div>
    </div>
-->
    <div class="footer">
	    <form method="post" action="{% url 'majorApp:navigation' %}">
            {% csrf_token %}
            <button type="submit" name="task" value="home">Home</button>
            <button type="submit" name="task" value="overview">Overview</button>
            <button type="submit" name="task" value="financials" >Financials</button>
            <button type="submit" name="task" value="fundamentals" >Fundamentals</button>
            <button type="submit" name="task" value="projections" >Projections</button>
        </form>
    </div>
        {%block content%}
        {% endblock %}
</body>

templates/majorApp/overview.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Investology-Overview{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.css">
    <link rel="stylesheet" href="{% static 'css/overview.css' %}">
</head>
<body>
{% include 'majorApp/navigation.html' %}
{% block content %}
<div class="chart-container">
    <div class="chart-header">
        <p style="color: black;"><b style="font-size: 30px;"><u>Summary of {{c_name}}</u></b><br><br>{{summary}}</p>
    </div>
</div>
<div class="card-container" style="left: 7.5; margin-left: 0px;">
    <div class="card" style="background-color: #4a90e2; color: white; align-items: normal">
            <h3>Total Employees </h3>
            <h3>{{ Total_Employees }}</h3>
    </div>
    <div class="card" style="background-color: #50e3c2; color: white;">
            <h4>{{ industry }}</h4>
            <h4>{{ sector }}</h4>
    </div>
    <div class="card" style="background-color: #f5a623; color: white;">
            <h3>Website</h3>
            <a>{{ website }}</a>
    </div>
</div>
<div class="pie_chart">
    <div class="chart-header">{{ pie_chart | safe }}</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
{% endblock %}
</body>

templates/majorApp/projections.html
{% load static %}

{% load custom_filters1 %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Investology-Projections{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/fundamentals.css' %}">
    <style>
        .plot-container {
            justify-content: center;
            margin: 50px 50px;
        }
    </style>
</head>
<body>
{% include 'majorApp/navigation.html' %}
{% block content %}
    <div class="container1">
        <div class="header1">
            <h1>{{ company_name }} Projections</h1>
        </div>
        <div class="links1">
            <a href="#">Website: {{website}}</a>
            <a href="#">NSE: {{company_name}}</a>
        </div>
        <div class="content1">
            <div class="info1">
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Current Price</span>
                        <span class="value1">₹ {{current_price|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Last Price</span>
                        <span class="value1">₹ {{yesterday_price|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">52 Week Low</span>
                        <span class="value1">₹ {{52_week_low|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">52 Week High</span>
                        <span class="value1">₹ {{52_week_high|floatformat:2}}</span>
                    </div>
                </div>
                <div class="row1">
                    <div class="col1">
                        <span class="label1">Today Open</span>
                        <span class="value1">₹ {{open|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Today High</span>
                        <span class="value1">₹ {{high|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Today Low</span>
                        <span class="value1">₹ {{low|floatformat:2}}</span>
                    </div>
                    <div class="col1">
                        <span class="label1">Today Close</span>
                        <span class="value1">₹ {{close|floatformat:2}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--
    <div class="container1">
            <div class="header1">
                <h1>{{ company_name }} 30 Days Projections</h1>
            </div>
            <div class="content1">
                <div class="info1">
                    <p style="color=black;">{{predicted_prices}}</p>
                </div>
            </div>
    </div>
    -->
<div class="plot-container">
    <div>{{ plotly_image1 | safe }}</div>
</div>

<div class="plot-container">
    <div>{{ plotly_image2 | safe }}</div>
</div>

<div class="plot-container">
    <div>{{ project | safe }}</div>
</div>

{% endblock %}

templates/majorApp/searchPage.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Investology-Search</title>
    <link rel="stylesheet" href="{% static 'css/searchPage.css' %}">
</head>
<body>
    <div class="container">
        <div class="title">Investology</div>
        <div class="search-box">
            {% if alert_message %}
            <script>
                alert("Redirecting to SearchPage. Please Enter Company Symbol!");
            </script>
            {% endif %}
            <form method="POST" action="{% url 'majorApp:overview' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select name="c_name" class="choose">
                        <option value="" selected>Select Company</option>
                        {% for option in options %}
                        <option value="{{ option.value }}">{{ option.text }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" name="search">Search</button>
                </div>
                <p class="disclaimer">Disclaimer: All content on this site is for informational purposes of a general nature only,
                    <br>and does not address any circumstances of any particular individual or entity</p>
            </form>
        </div>
    </div>
</body>
</html>